name: Keep clone up to date
variables:
  REMOTE_ADDR: 'https://github.com/COMP-4956-Project/MVC-Backend-Frontend.git'
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
          displayName: run_commands
        - bash: | 
            git checkout master
            git remote add repoGithub $(REMOTE_ADDR)
            git fetch repoGithub master
            git reset --hard repoGithub/master
            git pull --rebase repoGithub master